const asset = (name) => `/assets/shiuchit/${name}`;

export const projects = [
  {
    id: "wise-future-store-london",
    title: "Wise future store London",
    type: "Event",
    year: "2026",
    client: "Wise",
    duration: "1 week",
    roles: ["Motion Design", "Art Direction", "Set Design"],
    cover: asset("wise-future-store-london-cover.png"),
    gallery: [asset("wise-future-store-london-01.png"), asset("wise-future-store-london-03.png"), asset("wise-future-store-london-07.png")],
    youtubeId: "2RPVS-Zvx6Y",
    summary: "A visual record of Wise Future Stores on Oxford Street: its lime-green flagship, Wisdom Bar, immersive digital installations and Jenki matcha collaboration.",
    challenge: "Show a busy retail flagship without losing the clarity of the brand or the warmth of the people moving through it.",
    solution: "Wide exteriors establish the Oxford Street scale, environmental interiors explain the experience, and close lifestyle frames bring the story back to one-to-one moments at the Wisdom Bar.",
  },
  {
    id: "hublot-tourbillion",
    title: "Hublot Tourbillion",
    type: "Motion",
    eyebrow: "3D Motion",
    year: "2024",
    client: "Hublot Tourbillion",
    duration: "8 weeks",
    roles: ["3D Motion", "Procedural Animation", "Creative Direction"],
    cover: asset("form-and-matter-cover.png"),
    gallery: [asset("hublot-gallery-1.png"), asset("hublot-gallery-2.png")],
    youtubeId: "0M2HCrNehLY",
    summary: "A sleek, minimal and aspirational film focused on metallic surfaces, dark tones and the precise mechanical detail of a Hublot tourbillon.",
    challenge: "Communicate quality and craftsmanship without the language of a conventional sales film, creating a piece closer to an art film.",
    solution: "Elegant close-ups, controlled slow motion and immersive sound focus attention on the watch’s intricate construction and position the brand within luxury craft.",
  },
  {
    id: "aigc-for-midnite",
    title: "AIGC for Midnite",
    type: "Motion",
    eyebrow: "Brand Animation",
    year: "2026",
    client: "Midnite",
    duration: "2 weeks",
    roles: ["Motion Design", "Brand Identity", "Creative Direction"],
    cover: asset("kinetic-identity-cover.png"),
    gallery: [asset("midnite-gallery-1.png"), asset("midnite-gallery-2.png")],
    youtubeId: "NU2W1CMjTo0",
    summary: "A bold, digital-first campaign built around Midnite Green, surreal AIGC imagery, stylised 2D and 3D graphics, fast cuts and app-focused close-ups.",
    challenge: "Break through a crowded betting category without falling back on traditional bookmaker tropes, and make the work feel native to a younger audience.",
    solution: "Creative storytelling was paired with Google DeepMind’s Veo model to create futuristic, high-energy sequences that position the product as a modern alternative.",
  },
  {
    id: "motion-wheel",
    title: "Motion Wheel 2025",
    type: "Motion",
    eyebrow: "Motion Design",
    year: "2025",
    client: "Multiple",
    duration: "5 weeks",
    roles: ["3D Animation", "Art Direction"],
    cover: asset("fluid-spaces-cover.png"),
    gallery: [asset("motionwheel-gallery-1.png"), asset("motionwheel-gallery-2.png")],
    youtubeId: "CsQ7XcZDIoI",
    summary: "A high-energy reel moving from Midnite’s neon-fast visual language to the polished worlds of Samsung and Hublot, tied together by dynamic motion and modern colour.",
    challenge: "Show range across very different industries while retaining a recognisable creative voice and balancing AI experimentation with luxury cinematography.",
    solution: "A high-tempo edit, deliberate transitions, unified sound design and a driving score turn the varied projects into one cohesive cinematic pulse.",
  },
  {
    id: "samsung-skate-park",
    title: "Samsung skate park",
    type: "Event",
    year: "2024",
    client: "Samsung",
    duration: "4 weeks",
    roles: ["Art Direction", "Motion Design", "Graphic Design"],
    cover: asset("samsung-skate-park-cover.png"),
    gallery: [asset("samsung-skate-park-01.png"), asset("samsung-skate-park-05.png"), asset("samsung-skate-park-img-6140.mp4")],
    youtubeId: "gW9KfXGeqEQ",
    summary: "A modular visual world for Samsung’s skate-park experience, joining skateboard geometry, vivid colour, launch graphics and live-event energy around Galaxy Z Flip5.",
    challenge: "Unify patterns, UI-like icons, typography and documentary photography so the broad toolkit reads as one Samsung experience.",
    solution: "A controlled teal, mint, periwinkle, orange and coral palette grounds the system. Repeated deck geometry connects social, large-format LED and the live event.",
  },
  {
    id: "scholl-campaign",
    title: "Scholl campaign",
    type: "Shoot",
    eyebrow: "Art Direction",
    year: "2022",
    client: "Scholl",
    duration: "8 weeks",
    roles: ["Art Direction", "3D Animation", "Texturing"],
    cover: asset("organic-structure-cover.png"),
    gallery: [asset("scholl-gallery-1.png"), asset("scholl-gallery-2.png")],
    youtubeId: "yK5AQZ-CxZQ",
    summary: "A character-led campaign that contrasts everyday tension with relief, using a softly modelled 3D frog as an instantly memorable expression of comfort.",
    challenge: "Make pain relief feel emotional rather than technical, while ensuring the frog supports product trust instead of becoming a visual gimmick.",
    solution: "Expressive animation, gentle timing and tactile interactions place the character directly inside moments of relief, turning an abstract benefit into something felt.",
  },
  {
    id: "tug-of-war",
    title: "Tug of war",
    type: "Motion",
    eyebrow: "Annecy Animation Festival Selection",
    year: "2022",
    client: "Self-Initiated",
    duration: "6 weeks",
    roles: ["Character Design", "Illustration", "Art Direction"],
    cover: asset("type-in-motion-cover.png"),
    gallery: [asset("tug-of-war-gallery-1.png"), asset("tug-of-war-gallery-2.png")],
    youtubeId: "ubUqx19eCzg",
    summary: "A tactile frame-by-frame film where distinct characters learn to align their movement and unite against a large, chaotic monster.",
    challenge: "Keep complex action readable across multiple characters while making the emotional shift from internal conflict to collaboration feel earned.",
    solution: "Strong key poses and silhouettes anchor the action. Timing, spacing and direction gradually synchronise, using animation itself to express cooperation.",
  },
  {
    id: "aigc-iris",
    title: "AIGC for IRIS",
    type: "Motion",
    eyebrow: "Commercial",
    year: "2025",
    client: "IRIS Worldwide",
    duration: "2 weeks",
    roles: ["Motion Design", "VFX"],
    cover: asset("liquid-gold-cover.png"),
    gallery: [asset("aigc-iris-gallery-1.png"), asset("aigc-iris-gallery-2.png")],
    youtubeId: "172ziOzZcdE",
    summary: "A vibrant 60-second recap in which animated hosts Leanne and Menno guide viewers through IRIS Worldwide’s global business wins.",
    challenge: "Fit many brands and projects into a concise recap, giving each a distinct identity without losing the agency’s overall story.",
    solution: "AI-assisted characters, expressive movement, fast cuts and rhythmic transitions create personality and momentum while keeping the many brand moments coherent.",
  },
  {
    id: "adidas-ss23",
    title: "Adidas SS23",
    type: "Shoot",
    eyebrow: "Commercial",
    year: "2023",
    client: "Adidas",
    duration: "7 weeks",
    roles: ["Art Direction", "Editing", "VFX"],
    cover: asset("adidas-ss23-cover.png"),
    gallery: [asset("adidas-ss23-gallery-1.png"), asset("adidas-ss23-gallery-2.png")],
    youtubeId: "iC7DcDc_A9Y",
    summary: "An authentic outdoor campaign that lets landscape and physical effort demonstrate the grip, stability and durability of Adidas Terrex footwear.",
    challenge: "Prove performance without overt technical explanation, keeping the product visible while protecting the credibility expected by outdoor audiences.",
    solution: "Ground-level, immersive camerawork follows real steps, climbs and landings so repeated use becomes the evidence and the shoe feels like part of the body.",
  },
  {
    id: "asos-valentines-date-night",
    title: "ASOS Valentine’s Date Night",
    type: "Motion",
    eyebrow: "Motion Design",
    year: "2023",
    client: "ASOS",
    duration: "4 weeks",
    roles: ["Web Design", "E-commerce", "Art Direction"],
    cover: asset("maison-cover.png"),
    gallery: [asset("asos-valentines-gallery.png")],
    youtubeId: "XYVqoPoemi4",
    summary: "A bold, playful and socially native Valentine’s film built around confident styling, close details and quick cuts for a Gen-Z audience.",
    challenge: "Make the occasion feel relevant to an audience wary of romance clichés while keeping ASOS and the commercial intent clear.",
    solution: "The narrative centres confidence, individuality and the fun of getting ready, reframing Valentine’s Day as personal style rather than a conventional romance story.",
  },
];
